#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SOURCE_KEY="${1:-}"
CONFIG_PATH="${2:-./config.yaml}"

if [ -z "$SOURCE_KEY" ]; then
  echo '{"error":"missing_source_key"}'
  exit 2
fi

read_yaml() {
  python3 - <<PY
import sys, yaml
cfg = yaml.safe_load(open("$CONFIG_PATH"))
src = cfg['sources'].get("$SOURCE_KEY")
if not src:
    print()
    sys.exit(3)
print(src.get('base_url','') + (src.get('endpoint','') and src.get('endpoint','')))
PY
}

BASE_ENDPOINT="$(read_yaml)"
OUTDIR="/ancient_script_extraction/output/${SOURCE_KEY}"
mkdir -p "$OUTDIR"

ERROR_FILE="${OUTDIR}/error.json"
OUTPUT_FILE="${OUTDIR}/${SOURCE_KEY}_complete_glyphs.json"
VALIDATION_FILE="${OUTDIR}/validation_results.json"

write_error_and_exit() {
  local msg="$1"; local code="${2:-1}"
  jq -n --arg m "$msg" --arg c "$code" '{error: $m, exit_code: ($c|tonumber), timestamp: (now|todate)}' > "$ERROR_FILE"
  echo "WROTE $ERROR_FILE"
  exit "$code"
}

HTTP_RESULT="$(mktemp)"
if ! curl -sS --max-time 30 -w "%{http_code}" -o "$HTTP_RESULT" "$BASE_ENDPOINT"; then
  write_error_and_exit "http_request_failed"
fi
HTTP_CODE="$(tail -n1 "$HTTP_RESULT" | tr -d '\r\n' | sed -n '$p')"
BODY="$(cat "$HTTP_RESULT")"

if [[ "$HTTP_CODE" =~ ^[0-9]{3}$ ]]; then
  true
else
  HTTP_CODE="000"
fi

if [ "$HTTP_CODE" = "404" ]; then
  write_error_and_exit "http_404_not_found" 404
fi

if [ "$HTTP_CODE" = "000" ] || [ "$HTTP_CODE" = "000" ]; then
  write_error_and_exit "http_no_response" 500
fi

cat "$BODY" > "${OUTPUT_FILE}.raw"

if python3 - <<PY
import sys, json
s = open("${OUTPUT_FILE}.raw").read().strip()
try:
  doc = json.loads(s)
except Exception as e:
  print("BAD_JSON")
  sys.exit(4)
if not doc:
  print("EMPTY_ARRAY")
  sys.exit(5)
print("OK")
PY
then
  mv "${OUTPUT_FILE}.raw" "$OUTPUT_FILE"
else
  RET=$?
  if [ "$RET" -eq 4 ]; then
    write_error_and_exit "invalid_json_response" 4
  elif [ "$RET" -eq 5 ]; then
    write_error_and_exit "empty_array_response" 5
  else
    write_error_and_exit "unknown_response_validation_error" 6
  fi
fi

python3 - <<PY > "$VALIDATION_FILE"
import json, sys
data = json.load(open("$OUTPUT_FILE"))
if isinstance(data, dict):
    items = 1
else:
    items = len(data)
print(json.dumps({
  "glyph_count": items,
  "primary_source_present": True,
  "notes": "Autogenerated validation summary"
}))
PY

echo "SUCCESS: fetched $SOURCE_KEY -> $OUTPUT_FILE"
exit 0
